club/app/urls.py
from django.urls import path
from . import views
app_name ='app'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('alumnos/', views.AlumnosListView.as_view(), name='alumnos'),
    path('alumnos/paquetes/<uuid:id>/',views.paquetes,name='paquetes'),
    path('alumnos/paquetes/<uuid:id>/<uuid:paquete_id>/',views.clases,name='clases'),
    path('services/', views.services, name='services'),
    path('testimony/', views.testimony, name='testimony')
]

club/blog/urls.py
from django.urls import path
from . import views

app_name ='blog'
urlpatterns = [
    path('blog/',views.blog.as_view(),name='blog'),
    path('blog/<uuid:id>/',views.postDetail,name="post_detail"),
    path('contact/', views.contact,name="contact")

]

club/club/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Club de Tareas Admin"
admin.site.site_title = "Club de Tereas Portal"
admin.site.index_title = "Bienvenido al Club de tareas Admin"


urlpatterns = [
    path('', include('app.urls')),
    path('',include('blog.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

club/app/models.py
from django.db import models
import uuid
import datetime
from django.contrib.auth.models import  User

 # name of the foreign key field


class Sesion(models.Model):
    paquete_inscrito = models.ForeignKey('Paquete_Inscrito',related_name="sesiones",on_delete=models.CASCADE,null=True)
    asignatura = models.CharField(max_length=100)
    tiempo_de_inicio = models.DateTimeField(null=True,blank=True)
    tiempo_de_salida = models.DateTimeField(null=True,blank=True)
    observaciones = models.CharField(max_length=200,null=True,blank=True)

    def _get_tiempo_de_sesion(self):
        if self.tiempo_de_salida == None:
            return None
        return self.tiempo_de_salida - self.tiempo_de_inicio

    tiempo_de_sesion = property(_get_tiempo_de_sesion)

    class Meta:
        verbose_name = ("Sesion")
        verbose_name_plural = ("Sesiones")
        ordering = ['-tiempo_de_inicio']
    def __str__(self):
        return f'{self.asignatura}: duración: { self.tiempo_de_sesion}'

class Tipo_de_Paquete(models.Model):
    horas = models.IntegerField(default=1)

    class Meta:
        verbose_name = ("Tipo de Paquete")
        verbose_name_plural = ("Tipos de Paquetes")

    def __str__(self):
        return f'{self.horas} Horas'



class AlumnoProfile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="id del Alumno")
    #k_user = models.OneToOneField(User,on_delete=models.CASCADE)
    nombre =  models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    NIVEL_STATUS = (
         ('k','Kinder'),
         ('p','Primaria'),
         ('s','Secundaria'),
         ('b','bachillerato'),
         ('u','universidad'))
    nivel_academico = models.CharField(max_length=1,choices=NIVEL_STATUS,blank=True,help_text='Elige el nivel académico del alumno')

    class Meta:
        verbose_name = ("Perfil del Alumno")
        verbose_name_plural = ("Perfiles de los Alumnos")
        
    def __str__(self):
        return f'{self.nombre} { self.apellido}'


class Paquete_Inscrito(models.Model):
     id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="id del Paquete")
     #related_name='_clases_concluidas'
     alumno = models.ForeignKey('AlumnoProfile',on_delete=models.CASCADE,null=True)
     fecha_de_inscripcion = models.DateField(null=True,blank=True)
     horas_consumidas = models.DurationField(default=datetime.timedelta(days=0,hours=0,minutes=0))
     horas_restantes = models.DurationField(default=datetime.timedelta(days=0,hours=0,minutes=0))
     ESTADO_STATUS =(
     (True,'Activo'),
     (False,'Finalizado')
     )

     tipo_de_paquete = models.ForeignKey('Tipo_de_Paquete', on_delete=models.SET_NULL, null=True,help_text='Elige el tipo de paquete del alumno')
     #sesiones = models.ForeignKey('Sesion',on_delete=models.SET_NULL,null=True)
     status = models.BooleanField(default=True,choices=ESTADO_STATUS,blank=True,help_text="Elige el estado del paquete")

     class Meta:
         verbose_name = ("Paquete Inscrito")
         verbose_name_plural = ("Paquetes Inscritos")
         ordering = ['alumno__nombre']


     def __str__(self):
         if self.status == True:
             return f'{self.alumno} | Status: Activo'
         else:
            return f'{self.alumno} | Status: Finalizado'

club/blog/models.py
from django.db import models
import uuid
from django.contrib.auth.models import  User
from django.urls import reverse
from embed_video.fields import EmbedVideoField
# Create your models here.


class Post(models.Model):
    STATUS = (
    (0,'borrador'),
    (1,'publicado')
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="id del Post")
    titulo = models.CharField(max_length=200,unique=True)
    autor = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    update_on= models.DateTimeField(auto_now=True)
    imagen = models.ImageField(upload_to='post_image/%Y/%m/%d',blank=True)
    video = EmbedVideoField(blank=True)
    content = models.TextField()
    create_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS,default=0)

    class Meta:
        ordering = ['-create_on']

    def get_absolute_url(self):
            return reverse('blog:post_detail', kwargs={'id':self.id})

    def __str__(self):
        return self.titulo


class Comentario(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="id del comentario")
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comentarios')
    nombre = models.CharField(max_length=80)
    mensaje = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comentario de:{}'.format(self.nombre)

class Mensaje(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="id del mensaje")
    nombre = models.CharField(max_length=80)
    asunto = models.CharField(max_length=80)
    email = models.EmailField()
    body= models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']
    def __str__(self):
        return self.nombre

club/blog/forms.py
from .models import Comentario,Mensaje
from django import forms


class CommentForm(forms.Form):
    nombre = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'nombre'}))
    mensaje = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control','placeholder':'Mensaje'}))

class MensajeForm(forms.Form):
    nombre = forms.CharField(max_length= 50,widget=forms.TextInput(attrs={'class':'form-control','placeholder':"Nombre"}))
    asunto = forms.CharField(max_length= 50,widget=forms.TextInput(attrs={'class':'form-control','placeholder':"Asunto"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':"Email"}))
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control','placeholder':'Mensaje'}))

club/blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Post,Comentario,Mensaje
from .forms import CommentForm,MensajeForm
import uuid
from django.http import HttpResponseRedirect
from django.views.generic import (ListView)
from django.urls import reverse

class blog(ListView):
    model= Post
    template_name= 'blog/blog.html'
    context_object_name='posts'
    paginate_by= 3

    def get_queryset(self):
        return self.model.objects.filter(status=1).order_by('-create_on')
        #return Post.objects.filter(status=1).order_by('-create_on')

def contact(request):

    if request.method == 'POST':
        mensaje_form = MensajeForm(data=request.POST)
        if mensaje_form.is_valid():
            mensaje = Mensaje(nombre=request.POST["nombre"],asunto=request.POST["asunto"],email=request.POST["email"],body=request.POST["body"])
            mensaje.save()
            mensaje_form.cleaned_data
        return HttpResponseRedirect(reverse('blog:contact'))
    else:
        mensaje_form = MensajeForm()
        context = {
         'mensaje_form': mensaje_form
        }
        return render(request,'blog/contact.html',context)


def postDetail(request,id):
    post_object = get_object_or_404(Post,id=id)
    comentarios = post_object.comentarios.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = Comentario(post=post_object,nombre=request.POST["nombre"],mensaje=request.POST["mensaje"])
            new_comment.save();
            comment_form.cleaned_data
        return HttpResponseRedirect(post_object.get_absolute_url())
    else:
        comment_form= CommentForm()
    #obtengo todos los posts activos
    posts = Post.objects.filter(status=1)
    # los ordeno segun el numero de comentarios activos (mayor a menor)
    order_post_by_comments = sorted(posts,key= lambda post: len(post.comentarios.filter(active=True)),reverse=True)
    # me  aseguro que las lista de los post mas comentados sea como máximo 5 posts
    if len(order_post_by_comments) > 5 :
        order_post_by_comments = order_post_by_comments[:6]

    context = {
    'order_post_by_comments': order_post_by_comments,
    'posts': posts,
    'post': post_object,
    'comentarios': comentarios,
    'comment_form':comment_form
    }
    return render(request,'blog/detail_post.html',context)

club/app/templates/app/alumnos.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
<!--
background-image: url({% static 'app/images/system.jpg'%}); background-attachment: fixed; background-size: cover;
background-position: center center; background-repeat: no-repeat;-->
<section class="ftco-section ftco-project"  style="min-height: 600px;background:#31de79">
  <div class="container px-md-2">
    <div class="row justify-content-center">
      <div class="col-md-7 text-center heading-section  ftco-animate">

          <span class="subheading">Sistema</span>
        <h2 class="pb-4">Alumnos</h2>
      </div>
    </div>
<div class="input-group md-form form-s pl-0">
  <div class="container">

    <div class="row justify-content-center pb-3">

        <div class="col-md-5">
          <form method='GET' style="width:100%">
              <div class="input-group mb-3">
                  <input type="text" class="form-control" name="busqueda" placeholder="Escribe tu Id..." value="{{request.GET.busqueda}}">
                <div class="input-group-append">
                  <button class="btn btn-outline-secondary" type="submit" id="button-addon2"><i class="fa fa-search" aria-hidden="true"></i></button>
                </div>
                </div>
          </form>
          </div>


    </div>

  </div>


</div>

{% if  alumnos %}
<table  class="table table-hover table-sm table-bordered ftco-animate" style="background: white">
<!--Table head-->
<thead>
  <tr>
    <!--<th scope="col">#</th>-->
    <th scope="col">Nombre</th>
    <th scope="col">Apellido</th>
    <!--<th scope="col">Nivel Académico</th>-->
    <th scope="col">Paquetes</th>
  </tr>
</thead>
<!--Table head-->
<!--Table body-->
<tbody>
    {% for alumno in alumnos %}
     <tr style="">
       <!--<th scope="row"><i style="font-size: 25px" class="fa fa-user"></i></th>-->
       <td>{{ alumno.nombre }}</td>
       <td>{{ alumno.apellido }}</td>
       <td>
       <p class="mb-0"><a href="{% url 'app:paquetes' id=alumno.id %}" class="btn btn-primary">Detalles</a></p>
      </td>
     </tr>
    {% endfor %}
</tbody>
<!--Table body-->
</table>
{% endif %}
</div>
</section>

{% endblock content     %}

club/app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Club de tareas</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:url"           content="http://127.0.0.1:8000" />
    <meta property="og:type"          content="website" />
    <meta property="og:title"         content="Club de Tareas" />
    <meta property="og:description"   content="Centro de Tutorias para alumnos" />
    {% block meta_tag %}{% endblock%}
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'app/css/open-iconic-bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'app/css/animate.css'%}">
    <link rel="stylesheet" href="{% static 'app/css/search.css'%}">
    <link rel="stylesheet" href="{% static 'app/css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'app/css/owl.theme.default.min.css'%}">
    <link rel="stylesheet" href="{% static 'app/css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'app/css/aos.css'%}">
    <link rel="stylesheet" href="{% static 'app/css/ionicons.min.css'%}">
    <link rel="stylesheet" href="{% static 'app/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/fix.css' %}">
  </head>
  <body  data-target=".site-navbar-target" data-offset="300">
  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="index.html">Club de <span>Tareas</span></a>
	      <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav nav ml-auto">
	          <li class="nav-item"><a href="{% url 'app:home' %}" class="nav-link"><span>Home</span></a></li>
	          <li class="nav-item"><a href="{% url 'app:about' %}"  class="nav-link"><span>Acerca</span></a></li>
	          <li class="nav-item"><a href="{% url 'app:testimony' %}"  class="nav-link"><span>Testimonios</span></a></li>
	          <li class="nav-item"><a href="{% url 'app:services' %}" class="nav-link"><span>Servicios</span></a></li>
              <li class="nav-item"><a href="{% url 'blog:blog' %}" class="nav-link"><span>Blog</span></a></li>
	          <li class="nav-item"><a href="{% url 'app:alumnos' %}"  class="nav-link"><span>Alumnos</span></a></li>
	       <!--   <li class="nav-item"><a href="#blog-section" class="nav-link"><span>Blog</span></a></li>-->
	          <li class="nav-item"><a href="{% url 'blog:contact' %}"  class="nav-link"><span>Contacto</span></a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>

    {% block content %}{% endblock %}


    <footer class="ftco-footer ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">About DigiLab</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-4">
              <h2 class="ftco-heading-2">Links</h2>
              <ul class="list-unstyled">
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Home</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>About</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Services</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Projects</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Contact</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Services</h2>
              <ul class="list-unstyled">
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Design</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Development</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Business Strategy</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Data Analysis</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Graphic Design</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>



  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

  <div id="fb-root"></div>
  <script src="{% static 'app/js/jquery.min.js' %}"></script>
  <script src="{% static 'app/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'app/js/popper.min.js' %}"></script>
  <script src="{% static 'app/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'app/js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'app/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'app/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'app/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'app/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'app/js/aos.js'%}"></script>
  <script src="{% static 'app/js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'app/js/scrollax.min.js' %}"></script>
  <!-- <script src="{% static 'app/js/google-map.js' %}"></script> -->
  <script src="{% static 'app/js/main.js' %}"></script>
  <!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>-->
  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v5.0"></script>


  </body>
</html>

club/app/templates/app/blog.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
      <section class="ftco-section bg-light" id="blog-section">
            <div class="container">
              <div class="row justify-content-center mb-5 pb-5">
                <div class="col-md-7 heading-section text-center ftco-animate">
                  <span class="subheading">Blog</span>
                  <h2 class="mb-4">Nuestro Blog</h2>
                  <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
                </div>
              </div>
              <div class="row d-flex">
                {%for post in posts%}
                <div class="col-md-4 d-flex ftco-animate">
                	<div class="blog-entry justify-content-end">
                    <a href="single.html" class="block-20" style="background-image: url({{post.imagen.url}})">
                    </a>
                    <div class="text mt-3 float-right d-block">
                    	<div class="d-flex align-items-center pt-2 mb-4 topp">
                    		<div class="one mr-2">
                    			<span class="day">{{post.create_on.day}}</span>
                    		</div>
                    		<div class="two">
                    			<span class="yr">{{post.create_on.year}}</span>
                          {%if post.create_on.month == 1 %}
                          <span class="mos">Enero</span>
                          {%elif post.create_on.month == 2 %}
                              <span class="mos">Febrero</span>
                          {%elif post.create_on.month == 3 %}
                              <span class="mos">Marzo</span>
                          {%elif post.create_on.month == 4 %}
                              <span class="mos">Abril</span>
                          {%elif post.create_on.month == 5 %}
                              <span class="mos">Mayo</span>
                          {%elif post.create_on.month == 6 %}
                              <span class="mos">Junio</span>
                          {%elif post.create_on.month == 7 %}
                              <span class="mos">Julio</span>
                          {%elif post.create_on.month == 8 %}
                              <span class="mos">Agosto</span>
                          {%elif post.create_on.month == 9 %}
                              <span class="mos">Septiembre</span>
                          {%elif post.create_on.month == 10 %}
                              <span class="mos">Octubre</span>
                          {%elif post.create_on.month == 11 %}
                              <span class="mos">Noviembre</span>
                          {%else %}
                              <span class="mos">Dicembre</span>
                          {%endif%}
                    		</div>
                    	</div>
                      <h3 class="heading"><a href="single.html">{{ post.titulo}}</a></h3>
                      <p>{{post.content|truncatewords:10|linebreaks}}</p>
                      <div class="d-flex align-items-center mt-4 meta">
      	                <p class="mb-0"> <a href="{% url 'app:post_detail' id=post.id %}" class="btn btn-primary">Leer mas <span class="ion-ios-arrow-round-forward"></span></a></p>
      	                <p class="ml-auto mb-0">
      	                	<a href="#" class="mr-2">{{post.autor}}</a>
      	                	<a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a>
      	                </p>
                      </div>
                    </div>
                  </div>
                </div>
                 {%endfor%}
              </div>
            </div>
      </section>
{% endblock content%}

club/app/templates/app/paquetes.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}

<section class="ftco-section ftco-project" style="background:#31de79">

		<div class="container px-md-5">
				<p class="info-alumno ftco-animate" style="text-transform: uppercase; font-size: 25px">
					Historial de  Paquetes suscritos del  Alumno: {{ student.nombre }} {{ student.apellido}}
				</p>
				<button type="button" class="btn btn-primary btn-circle">
				</button> <span style="color: white" class="ftco-animate">Paquete Activo</span><br>
				<button type="button" class="btn btn-danger btn-circle">
				</button>
				<span style="color:white" class="ftco-animate">Paquete Culminado</span>
				<div style="width: 100%;height:20px;"></div>
				<ul class="list-group ftco-animate">
					{% for paquete in paquetes %}
					 {% if paquete.status %}
					 <li class="list-group-item" style="background-color: #3cb371;color:white"> Tipo de paquete: {{ paquete.tipo_de_paquete }}</li>
					 {%else%}
					 <li class="list-group-item" style="background-color: #de2d29;color: white"> Tipo de paquete: {{ paquete.tipo_de_paquete }}</li>
					 {% endif%}
           <li class="list-group-item"> Fecha de Inscripcion: {{ paquete.fecha_de_inscripcion }}</li>
					 <li class="list-group-item"> Horas consumidas: {{ paquete.horas_consumidas }} Hrs</li>
					 <li class="list-group-item"> Horas restantes: {{ paquete.horas_restantes }} Hrs</li>

					 {% if paquete.status%}
					 <li class="list-group-item">Status: Activo</li>
					 {% else %}
					 <li class="list-group-item" >Status: Culminado</li>
					 {% endif%}
					 <li class="list-group-item mb-5">
						 <a href="{% url 'app:clases' id=student.id paquete_id=paquete.id %}">
				     <button type="button" class="btn btn-primary"">Ver Clases </button>
				     </a>
					 </li>
					{% endfor %}
				</ul>
				<div class="mt-5" style="height: 40px; width: 100%; position:relative">
					<a href="{% url 'app:alumnos' %}?busqueda={{return_query}}" style="position: absolute; right:0">

					<button type="button" class="btn btn-primary" style="font-size:15px;">
								<i class="fa fa-chevron-left"></i> Ir Alumnos</button>
					</a>
				</div>

		</div>

</section>

{% endblock content     %}